# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestProfile1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_profile1(self):
    # Set window size even larger than before
    self.driver.set_window_size(1400, 1800)
    
    # Load the page
    self.driver.get("http://localhost/miniproject2/database%20gym/login2.php")
    
    # Login with simplified steps
    self.driver.find_element(By.NAME, "email").send_keys("h4hari2003@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("Hari@123")
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    
    # Wait for page to load after login
    WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.CLASS_NAME, "view-full-profile-btn"))
    )
    
    # Click view complete profile
    self.driver.find_element(By.CLASS_NAME, "view-full-profile-btn").click()
    
    # Wait for page to load
    time.sleep(2)
    
    # Try using JavaScript to click the button directly instead of Selenium's click method
    edit_button = self.driver.find_element(By.LINK_TEXT, "Edit Profile")
    self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", edit_button)
    time.sleep(1)
    self.driver.execute_script("arguments[0].click();", edit_button)
  
