# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMemberassign():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_memberassign(self):
    self.driver.get("http://localhost/miniproject2/database%20gym/login2.php")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("admin@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("admin@123")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .btn-primary").click()
    self.driver.find_element(By.NAME, "member_ids[]").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mt-3 > .admin-button").click()
    assert self.driver.switch_to.alert.text == "Members assigned successfully!"
  
